using CsvHelper;
using CsvHelper.Configuration;
using Ethanol.Artifacts;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reactive.Linq;

namespace Ethanol.Providers
{

    public static class CsvArtifactProvider
    {
        /// <summary>
        /// Creates an artifact provider based on the supplied arguments.
        /// </summary>
        /// <param name="artifactType"></param>
        /// <param name="filename"></param>
        /// <param name="formatString"></param>
        /// <returns></returns>
        public static IArtifactProvider CreateArtifactSource(Type artifactType, string filename)
        {
            var genericType = typeof(CsvArtifactProvider<>);
            Type constructed = genericType.MakeGenericType(new[] { artifactType });
            object o = Activator.CreateInstance(type: constructed, args: filename);
            return o as IArtifactProvider;
        }
    }
    /// <summary>
    /// Represents a data source based on CSV file that provides artifacts of type <typeparamref name="TArtifact"/>.
    /// Artifact classes have defined properties which corresponds to CSV fields generated by "nfdump -o csv" command.
    /// The header must be present in the CSV file.
    /// </summary>
    public class CsvArtifactProvider<TArtifact> : IArtifactProvider<TArtifact> where TArtifact : Artifact
    {
        readonly string _filename;
        private List<TArtifact> _artifacts;

        /// <summary>
        /// Creates a new CSV artifact provider. 
        /// </summary>
        /// <param name="filename">Source filename of the CSV data.</param>
        public CsvArtifactProvider(string filename)
        {
            _filename = filename ?? throw new ArgumentNullException(nameof(filename));
        }

        void Load()
        {
            var config = new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                HasHeaderRecord = true,
                TrimOptions = TrimOptions.Trim,
                MissingFieldFound = OnMissingField,
            };

            using (var reader = new StreamReader(_filename))
            {
                using (var csv = new CsvReader(reader, config))
                {
                    _artifacts = csv.GetRecords<TArtifact>().Select((x,i) => { x.Id =$"{i + 1}"; return x; } ).ToList();                    
                }
            }
        }


        public static IEnumerable<TArtifact> LoadFrom(string filename)
        {
            var config = new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                HasHeaderRecord = true,
                TrimOptions = TrimOptions.Trim,
                MissingFieldFound = OnMissingField,
            };

            using (var reader = new StreamReader(filename))
            {
                using (var csv = new CsvReader(reader, config))
                {
                    int id = 0;
                    csv.Read();
                    csv.ReadHeader();
                    while (csv.Read())
                    {
                        var record = csv.GetRecord<TArtifact>();
                        record.Id = (++id).ToString();
                        yield return record;
                    }
                }
            }
        }


        private static void OnMissingField(MissingFieldFoundArgs args)
        {
            /* Do nothing */
        }

        public IObservable<TTarget> GetObservable<TTarget>() where TTarget : Artifact
        {
            return GetOrLoadArtifacts().Cast<TTarget>().ToObservable();
        }


        IList<TArtifact> GetOrLoadArtifacts()
        {
            if (_artifacts == null) Load();
            return _artifacts; 
        }

        public IObservable<TArtifact> GetObservable()
        {
            return GetOrLoadArtifacts().ToObservable();
        }

        public Type ArtifactType => typeof(TArtifact);

        public string Source => $"file://{Path.GetFullPath(this._filename)}";
    }
}