using Ethanol.ContextBuilder.Context;
using Ethanol.ContextBuilder.Plugins.Attributes;
using System.Threading;

namespace Ethanol.ContextBuilder.Readers
{
    // TODO: Implement this class enabling to read SUricata produced NDJSON.
    [Plugin(PluginCategory.Reader, "SuricataJson", "Reads NDJSON generated by Suricata tool.")]
    class SuricataReader : BaseFlowReader<IpFlow>
    {
        protected override void Close()
        {
            throw new System.NotImplementedException();
        }

        protected override void Open()
        {
            throw new System.NotImplementedException();
        }

        protected override bool TryGetNextRecord(CancellationToken ct, out IpFlow record)
        {
            throw new System.NotImplementedException();
        }
    }
}
